hosts: all
gather_facts: False
become: yes
  
tasks:
  - name: Install Python 2
    raw: test -e /usr/bin/python || (yum update -y && yum install -y python2)

  - name: Install Java 11
    apt:
      name: openjdk-11-jdk
      state: present

roles:
  - Install